name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      
    - name: Build
      run: make
      
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3.0.0
      with:
        name: luaos.cpio.gz
        path: workdir/out.cpio.gz
        if-no-files-found: error
